# Generated by Django 5.1.7 on 2025-03-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('flowers', 'Flowers'), ('technology', 'Technology'), ('education', 'Education'), ('animals', 'Animals'), ('historical', 'Historical Places'), ('others', 'Others')], default='others', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
