# Generated by Django 5.1.7 on 2025-03-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_product_category_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('flowers', 'Flowers'), ('technology', 'Technology'), ('education', 'Education'), ('animals', 'Animals'), ('historical', 'Historical Places'), ('natural', 'Natural Scene'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
